export const MAX_LIMIT = 50;

export enum JobTitles {
  generalManager = "general manager",
  supervisor = "supervisor",
  accommodationSupervisor = "accommodation supervisor",
  reception = "reception",
  housekeeper = "housekeeper",
  security = "security",
  restaurantSupervisor = "restaurant supervisor",
  cashier = "cashier",
  waiter = "waiter",
  chef = "chef",
  cook = "cook",
  steward = "steward",
  trainee = "trainee",
  handyman = "handyman",
  storekeeper = "storekeeper",
  softwareAdmin = "software admin",
}
export const JobTitlesMapping: Record<string, JobTitles> = {
  "general manager": JobTitles.generalManager,
  supervisor: JobTitles.supervisor,
  "accommodation supervisor": JobTitles.accommodationSupervisor,
  reception: JobTitles.reception,
  housekeeper: JobTitles.housekeeper,
  security: JobTitles.security,
  "restaurant supervisor": JobTitles.restaurantSupervisor,
  cashier: JobTitles.cashier,
  waiter: JobTitles.waiter,
  chef: JobTitles.chef,
  cook: JobTitles.cook,
  steward: JobTitles.steward,
  trainee: JobTitles.trainee,
  handyman: JobTitles.handyman,
  storekeeper: JobTitles.storekeeper,
  "software admin": JobTitles.softwareAdmin,
};

export enum EmployeePermissions {
  registerGuest = "register guest",
  updateGuestInfo = "update guest info",
  createRoom = "create room",
  updateRoomInfo = "update room info",
  updateRoomStatus = "update room status",

  bookingARoom = "booking a room",
  giftBookingARoom = "gift booking a room",
  voidBookingARoom = "void booking a room",
  updateBookingInfo = "update booking info",
  updateBookingPrice = "update booking price",

  acceptAccommodationPayment = "accept accommodation payment",
  updateAccommodationPayment = "update accommodation payment",

  makeMenu = "make menu",
  updateMenu = "update menu",
  updateMenuPrice = "update menu price",

  viewMyOrder = "view my order",
  viewAllOrder = "view all order",
  postOrder = "post order",
  updateOrder = "update order",
  updateAllOrder = "update all order",
  giftOrder = "gift order",
  voidOrder = "void order",
  transferOrder = "transfer order",

  acceptRestaurantPayment = "accept restaurant payment",
  updateRestaurantPayment = "update restaurant payment",

  addItemToInventory = "add item to inventory",
  updateItemInfo = "update item info",

  makeMenuVsRecipe = "make menu vs recipe",
  spoilageMiscellaneousUsage = "spoilage miscellaneous usage",

  issueItem = "issue item",
  updateIssue = "update issue",

  purchaseItem = "purchase item",
  updatePurchase = "update purchase",

  registerEmployee = "register employee",
  updateEmployeeInfo = "update employee info",
  updateEmployeePermissions = "update employee permission",

  addExpense = "add expense",
  updateExpense = "update expense",

  verifyPayment = "verify payment",
  generateMyReport = "generate my report",
  generateAccommodationReport = "generate accommodation report",
  generateRestaurantReport = "generate restaurant report",
  generateInventoryReport = "generate inventory report",
  generateGeneralReport = "generate general report",
}
export const EmployeePermissionsMapping: Record<string, EmployeePermissions> = {
  "register guest": EmployeePermissions.registerGuest,
  "update guest info": EmployeePermissions.updateGuestInfo,
  "create room": EmployeePermissions.createRoom,
  "update room info": EmployeePermissions.updateRoomInfo,
  "update room status": EmployeePermissions.updateRoomStatus,

  "booking a room": EmployeePermissions.bookingARoom,
  "gift booking a room": EmployeePermissions.giftBookingARoom,
  "void booking a room": EmployeePermissions.voidBookingARoom,
  "update booking info": EmployeePermissions.updateBookingInfo,
  "update booking price": EmployeePermissions.updateBookingPrice,

  "accept accommodation payment": EmployeePermissions.acceptAccommodationPayment,
  "update accommodation payment": EmployeePermissions.updateAccommodationPayment,

  "make menu": EmployeePermissions.makeMenu,
  "update menu": EmployeePermissions.updateMenu,
  "update menu price": EmployeePermissions.updateMenuPrice,

  "view my order": EmployeePermissions.viewMyOrder,
  "view all order": EmployeePermissions.viewAllOrder,
  "post order": EmployeePermissions.postOrder,
  "update order": EmployeePermissions.updateOrder,
  "update all order": EmployeePermissions.updateAllOrder,
  "gift order": EmployeePermissions.giftOrder,
  "void order": EmployeePermissions.voidOrder,
  "transfer order": EmployeePermissions.transferOrder,

  "accept restaurant payment": EmployeePermissions.acceptRestaurantPayment,
  "update restaurant payment": EmployeePermissions.updateRestaurantPayment,

  "add item to inventory": EmployeePermissions.addItemToInventory,
  "update item info": EmployeePermissions.updateItemInfo,

  "make menu vs recipe": EmployeePermissions.makeMenuVsRecipe,
  "spoilage miscellaneous usage": EmployeePermissions.spoilageMiscellaneousUsage,

  "issue item": EmployeePermissions.issueItem,
  "update issue": EmployeePermissions.updateIssue,

  "purchase item": EmployeePermissions.purchaseItem,
  "update purchase": EmployeePermissions.updatePurchase,

  "register employee": EmployeePermissions.registerEmployee,
  "update employee info": EmployeePermissions.updateEmployeeInfo,
  "update employee permission": EmployeePermissions.updateEmployeePermissions,

  "add expense": EmployeePermissions.addExpense,
  "update expense": EmployeePermissions.updateExpense,

  "verify payment": EmployeePermissions.verifyPayment,
  "generate my report": EmployeePermissions.generateMyReport,
  "generate accommodation report": EmployeePermissions.generateAccommodationReport,
  "generate restaurant report": EmployeePermissions.generateRestaurantReport,
  "generate inventory report": EmployeePermissions.generateInventoryReport,
  "generate general report": EmployeePermissions.generateGeneralReport,
};

export enum RoomTypes {
  single = "single",
  double = "double",
  twin = "twin",
  triple = "triple",
  deluxe = "deluxe",
  family = "family",
  executive = "executive",
}
export const RoomTypesMapping: Record<string, RoomTypes> = {
  single: RoomTypes.single,
  double: RoomTypes.double,
  twin: RoomTypes.twin,
  triple: RoomTypes.triple,
  deluxe: RoomTypes.deluxe,
  family: RoomTypes.family,
  executive: RoomTypes.executive,
};

export enum OccupancyStatuses {
  vacant = "vacant",
  checkIn = "check-in",
  occupied = "occupied",
  checkOut = "check-out",
  reserved = "reserved",
  blocked = "blocked",
  maintenance = "maintenance",
}
export const OccupancyStatusesMapping: Record<string, OccupancyStatuses> = {
  vacant: OccupancyStatuses.vacant,
  "check-in": OccupancyStatuses.checkIn,
  occupied: OccupancyStatuses.occupied,
  "check-out": OccupancyStatuses.checkOut,
  reserved: OccupancyStatuses.reserved,
  blocked: OccupancyStatuses.blocked,
  maintenance: OccupancyStatuses.maintenance,
};

export enum ErrorTypes {
  CONTINUE = "CONTINUE",
  SWITCHING_PROTOCOLS = "SWITCHING_PROTOCOLS",
  PROCESSING = "PROCESSING",
  OK = "OK",
  CREATED = "CREATED",
  ACCEPTED = "ACCEPTED",
  NON_AUTHORITATIVE_INFORMATION = "NON_AUTHORITATIVE_INFORMATION",
  NO_CONTENT = "NO_CONTENT",
  RESET_CONTENT = "RESET_CONTENT",
  PARTIAL_CONTENT = "PARTIAL_CONTENT",
  MULTI_STATUS = "MULTI_STATUS",
  MULTIPLE_CHOICES = "MULTIPLE_CHOICES",
  MOVED_PERMANENTLY = "MOVED_PERMANENTLY",
  MOVED_TEMPORARILY = "MOVED_TEMPORARILY",
  SEE_OTHER = "SEE_OTHER",
  NOT_MODIFIED = "NOT_MODIFIED",
  USE_PROXY = "USE_PROXY",
  TEMPORARY_REDIRECT = "TEMPORARY_REDIRECT",
  PERMANENT_REDIRECT = "PERMANENT_REDIRECT",
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  PAYMENT_REQUIRED = "PAYMENT_REQUIRED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
  NOT_ACCEPTABLE = "NOT_ACCEPTABLE",
  PROXY_AUTHENTICATION_REQUIRED = "PROXY_AUTHENTICATION_REQUIRED",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
  CONFLICT = "CONFLICT",
  GONE = "GONE",
  LENGTH_REQUIRED = "LENGTH_REQUIRED",
  PRECONDITION_FAILED = "PRECONDITION_FAILED",
  REQUEST_TOO_LONG = "REQUEST_TOO_LONG",
  REQUEST_URI_TOO_LONG = "REQUEST_URI_TOO_LONG",
  UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE",
  REQUESTED_RANGE_NOT_SATISFIABLE = "REQUESTED_RANGE_NOT_SATISFIABLE",
  EXPECTATION_FAILED = "EXPECTATION_FAILED",
  IM_A_TEAPOT = "IM_A_TEAPOT",
  INSUFFICIENT_SPACE_ON_RESOURCE = "INSUFFICIENT_SPACE_ON_RESOURCE",
  METHOD_FAILURE = "METHOD_FAILURE",
  MISDIRECTED_REQUEST = "MISDIRECTED_REQUEST",
  UNPROCESSABLE_ENTITY = "UNPROCESSABLE_ENTITY",
  LOCKED = "LOCKED",
  FAILED_DEPENDENCY = "FAILED_DEPENDENCY",
  PRECONDITION_REQUIRED = "PRECONDITION_REQUIRED",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  REQUEST_HEADER_FIELDS_TOO_LARGE = "REQUEST_HEADER_FIELDS_TOO_LARGE",
  UNAVAILABLE_FOR_LEGAL_REASONS = "UNAVAILABLE_FOR_LEGAL_REASONS",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  BAD_GATEWAY = "BAD_GATEWAY",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT",
  HTTP_VERSION_NOT_SUPPORTED = "HTTP_VERSION_NOT_SUPPORTED",
  INSUFFICIENT_STORAGE = "INSUFFICIENT_STORAGE",
  NETWORK_AUTHENTICATION_REQUIRED = "NETWORK_AUTHENTICATION_REQUIRED",
}

export enum HTTPCodes {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  MOVED_TEMPORARILY = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  REQUEST_TOO_LONG = 413,
  REQUEST_URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  IM_A_TEAPOT = 418,
  INSUFFICIENT_SPACE_ON_RESOURCE = 419,
  METHOD_FAILURE = 420,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  INSUFFICIENT_STORAGE = 507,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
}
export const HTTPCodesMapping: Record<string, HTTPCodes> = {
  CONTINUE: HTTPCodes.CONTINUE,
  SWITCHING_PROTOCOLS: HTTPCodes.SWITCHING_PROTOCOLS,
  PROCESSING: HTTPCodes.PROCESSING,
  OK: HTTPCodes.OK,
  CREATED: HTTPCodes.CREATED,
  ACCEPTED: HTTPCodes.ACCEPTED,
  NON_AUTHORITATIVE_INFORMATION: HTTPCodes.NON_AUTHORITATIVE_INFORMATION,
  NO_CONTENT: HTTPCodes.NO_CONTENT,
  RESET_CONTENT: HTTPCodes.RESET_CONTENT,
  PARTIAL_CONTENT: HTTPCodes.PARTIAL_CONTENT,
  MULTI_STATUS: HTTPCodes.MULTI_STATUS,
  MULTIPLE_CHOICES: HTTPCodes.MULTIPLE_CHOICES,
  MOVED_PERMANENTLY: HTTPCodes.MOVED_PERMANENTLY,
  MOVED_TEMPORARILY: HTTPCodes.MOVED_TEMPORARILY,
  SEE_OTHER: HTTPCodes.SEE_OTHER,
  NOT_MODIFIED: HTTPCodes.NOT_MODIFIED,
  USE_PROXY: HTTPCodes.USE_PROXY,
  TEMPORARY_REDIRECT: HTTPCodes.TEMPORARY_REDIRECT,
  PERMANENT_REDIRECT: HTTPCodes.PERMANENT_REDIRECT,
  BAD_REQUEST: HTTPCodes.BAD_REQUEST,
  UNAUTHORIZED: HTTPCodes.UNAUTHORIZED,
  PAYMENT_REQUIRED: HTTPCodes.PAYMENT_REQUIRED,
  FORBIDDEN: HTTPCodes.FORBIDDEN,
  NOT_FOUND: HTTPCodes.NOT_FOUND,
  METHOD_NOT_ALLOWED: HTTPCodes.METHOD_NOT_ALLOWED,
  NOT_ACCEPTABLE: HTTPCodes.NOT_ACCEPTABLE,
  PROXY_AUTHENTICATION_REQUIRED: HTTPCodes.PROXY_AUTHENTICATION_REQUIRED,
  REQUEST_TIMEOUT: HTTPCodes.REQUEST_TIMEOUT,
  CONFLICT: HTTPCodes.CONFLICT,
  GONE: HTTPCodes.GONE,
  LENGTH_REQUIRED: HTTPCodes.LENGTH_REQUIRED,
  PRECONDITION_FAILED: HTTPCodes.PRECONDITION_FAILED,
  REQUEST_TOO_LONG: HTTPCodes.REQUEST_TOO_LONG,
  REQUEST_URI_TOO_LONG: HTTPCodes.REQUEST_URI_TOO_LONG,
  UNSUPPORTED_MEDIA_TYPE: HTTPCodes.UNSUPPORTED_MEDIA_TYPE,
  REQUESTED_RANGE_NOT_SATISFIABLE: HTTPCodes.REQUESTED_RANGE_NOT_SATISFIABLE,
  EXPECTATION_FAILED: HTTPCodes.EXPECTATION_FAILED,
  IM_A_TEAPOT: HTTPCodes.IM_A_TEAPOT,
  INSUFFICIENT_SPACE_ON_RESOURCE: HTTPCodes.INSUFFICIENT_SPACE_ON_RESOURCE,
  METHOD_FAILURE: HTTPCodes.METHOD_FAILURE,
  MISDIRECTED_REQUEST: HTTPCodes.MISDIRECTED_REQUEST,
  UNPROCESSABLE_ENTITY: HTTPCodes.UNPROCESSABLE_ENTITY,
  LOCKED: HTTPCodes.LOCKED,
  FAILED_DEPENDENCY: HTTPCodes.FAILED_DEPENDENCY,
  PRECONDITION_REQUIRED: HTTPCodes.PRECONDITION_REQUIRED,
  TOO_MANY_REQUESTS: HTTPCodes.TOO_MANY_REQUESTS,
  REQUEST_HEADER_FIELDS_TOO_LARGE: HTTPCodes.REQUEST_HEADER_FIELDS_TOO_LARGE,
  UNAVAILABLE_FOR_LEGAL_REASONS: HTTPCodes.UNAVAILABLE_FOR_LEGAL_REASONS,
  INTERNAL_SERVER_ERROR: HTTPCodes.INTERNAL_SERVER_ERROR,
  NOT_IMPLEMENTED: HTTPCodes.NOT_IMPLEMENTED,
  BAD_GATEWAY: HTTPCodes.BAD_GATEWAY,
  SERVICE_UNAVAILABLE: HTTPCodes.SERVICE_UNAVAILABLE,
  GATEWAY_TIMEOUT: HTTPCodes.GATEWAY_TIMEOUT,
  HTTP_VERSION_NOT_SUPPORTED: HTTPCodes.HTTP_VERSION_NOT_SUPPORTED,
  INSUFFICIENT_STORAGE: HTTPCodes.INSUFFICIENT_STORAGE,
  NETWORK_AUTHENTICATION_REQUIRED: HTTPCodes.NETWORK_AUTHENTICATION_REQUIRED,
};
